server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.131:3306/tensquare_base?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka
  instance:
    preferIpAddress: true